//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoArtifactLights.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoArtifactLights.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Press ~INPUT_CONTEXT~ to buy weapons. 的本地化字符串。
        /// </summary>
        public static string AmmuOpenShop {
            get {
                return ResourceManager.GetString("AmmuOpenShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pistol Ammo x100 的本地化字符串。
        /// </summary>
        public static string AmmuPistol {
            get {
                return ResourceManager.GetString("AmmuPistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard pistol, suitable for self defense. 的本地化字符串。
        /// </summary>
        public static string AmmuPistolSubtitle {
            get {
                return ResourceManager.GetString("AmmuPistolSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pump Shotgun Ammo x50 的本地化字符串。
        /// </summary>
        public static string AmmuPumpShotgun {
            get {
                return ResourceManager.GetString("AmmuPumpShotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard shotgun for self defense purposes. 的本地化字符串。
        /// </summary>
        public static string AmmuPumpShotgunSubtitle {
            get {
                return ResourceManager.GetString("AmmuPumpShotgunSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weapon Shop 的本地化字符串。
        /// </summary>
        public static string AmmuSubtitle {
            get {
                return ResourceManager.GetString("AmmuSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AmmuNation 的本地化字符串。
        /// </summary>
        public static string AmmuTitle {
            get {
                return ResourceManager.GetString("AmmuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Armed NPC Kill Bonus +$10 的本地化字符串。
        /// </summary>
        public static string ArmedBonus {
            get {
                return ResourceManager.GetString("ArmedBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have enough money for this. 的本地化字符串。
        /// </summary>
        public static string BuyNoMoney {
            get {
                return ResourceManager.GetString("BuyNoMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Carbine Rifle 的本地化字符串。
        /// </summary>
        public static string DifficultyCarbineRifle {
            get {
                return ResourceManager.GetString("DifficultyCarbineRifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Difficulty Changed 的本地化字符串。
        /// </summary>
        public static string DifficultyChange {
            get {
                return ResourceManager.GetString("DifficultyChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Easy 的本地化字符串。
        /// </summary>
        public static string DifficultyEasy {
            get {
                return ResourceManager.GetString("DifficultyEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hard 的本地化字符串。
        /// </summary>
        public static string DifficultyHard {
            get {
                return ResourceManager.GetString("DifficultyHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Difficulty has been upgraded to {0}. Ambient NPCs will now use {0}. 的本地化字符串。
        /// </summary>
        public static string DifficultyHelp {
            get {
                return ResourceManager.GetString("DifficultyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initial 的本地化字符串。
        /// </summary>
        public static string DifficultyInitial {
            get {
                return ResourceManager.GetString("DifficultyInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Micro SMGs 的本地化字符串。
        /// </summary>
        public static string DifficultyMicroSmg {
            get {
                return ResourceManager.GetString("DifficultyMicroSmg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nether 的本地化字符串。
        /// </summary>
        public static string DifficultyNether {
            get {
                return ResourceManager.GetString("DifficultyNether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        public static string DifficultyNormal {
            get {
                return ResourceManager.GetString("DifficultyNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pump Shotguns 的本地化字符串。
        /// </summary>
        public static string DifficultyPumpShotgun {
            get {
                return ResourceManager.GetString("DifficultyPumpShotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rocket Launchers 的本地化字符串。
        /// </summary>
        public static string DifficultyRPG {
            get {
                return ResourceManager.GetString("DifficultyRPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Difficulty has been upgraded to {0}. 的本地化字符串。
        /// </summary>
        public static string DifficultyShard {
            get {
                return ResourceManager.GetString("DifficultyShard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NoArtifactLights has encountered error and must exit. 的本地化字符串。
        /// </summary>
        public static string ExceptionMain {
            get {
                return ResourceManager.GetString("ExceptionMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NoArtifactLights menu has encountered error and menu is disabled. 的本地化字符串。
        /// </summary>
        public static string ExceptionMenu {
            get {
                return ResourceManager.GetString("ExceptionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have killed a person. Once you killed amount of persons, the difficulty will upgrade. 的本地化字符串。
        /// </summary>
        public static string FirstKill {
            get {
                return ResourceManager.GetString("FirstKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The game has been ~b~loaded~s~. 的本地化字符串。
        /// </summary>
        public static string GameLoaded {
            get {
                return ResourceManager.GetString("GameLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The game has been ~b~saved~s~. 的本地化字符串。
        /// </summary>
        public static string GameSaved {
            get {
                return ResourceManager.GetString("GameSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Views current cash. 的本地化字符串。
        /// </summary>
        public static string ItemCashSubtitle {
            get {
                return ResourceManager.GetString("ItemCashSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cash 的本地化字符串。
        /// </summary>
        public static string ItemCashTitle {
            get {
                return ResourceManager.GetString("ItemCashTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Call for police assistence. 的本地化字符串。
        /// </summary>
        public static string ItemCopsSubtitle {
            get {
                return ResourceManager.GetString("ItemCopsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Call for Cops 的本地化字符串。
        /// </summary>
        public static string ItemCopsTitle {
            get {
                return ResourceManager.GetString("ItemCopsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Difficulty 的本地化字符串。
        /// </summary>
        public static string ItemDifficulty {
            get {
                return ResourceManager.GetString("ItemDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Views current difficulty. 的本地化字符串。
        /// </summary>
        public static string ItemDIfficultySubtitle {
            get {
                return ResourceManager.GetString("ItemDIfficultySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kills 的本地化字符串。
        /// </summary>
        public static string ItemKills {
            get {
                return ResourceManager.GetString("ItemKills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Views current kills. 的本地化字符串。
        /// </summary>
        public static string ItemKillsSubtitle {
            get {
                return ResourceManager.GetString("ItemKillsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sets whether the lights have out of San Andreas or not. 的本地化字符串。
        /// </summary>
        public static string ItemLightsSubtitle {
            get {
                return ResourceManager.GetString("ItemLightsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blackout 的本地化字符串。
        /// </summary>
        public static string ItemLightsTitle {
            get {
                return ResourceManager.GetString("ItemLightsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loads the game from save. 的本地化字符串。
        /// </summary>
        public static string ItemLoadSubtitle {
            get {
                return ResourceManager.GetString("ItemLoadSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Game 的本地化字符串。
        /// </summary>
        public static string ItemLoadTitle {
            get {
                return ResourceManager.GetString("ItemLoadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saves the current game status. 的本地化字符串。
        /// </summary>
        public static string ItemSaveSubtitle {
            get {
                return ResourceManager.GetString("ItemSaveSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Game 的本地化字符串。
        /// </summary>
        public static string ItemSaveTitle {
            get {
                return ResourceManager.GetString("ItemSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sells current vehicle. You will receive some dollars. 的本地化字符串。
        /// </summary>
        public static string ItemSellCarSubtitle {
            get {
                return ResourceManager.GetString("ItemSellCarSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sell Current Vehicle 的本地化字符串。
        /// </summary>
        public static string ItemSellCarTitle {
            get {
                return ResourceManager.GetString("ItemSellCarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Menu 的本地化字符串。
        /// </summary>
        public static string MenuMainTitle {
            get {
                return ResourceManager.GetString("MenuMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have a save file. 的本地化字符串。
        /// </summary>
        public static string NoSave {
            get {
                return ResourceManager.GetString("NoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to NoArtifactLights survival modification.  的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pistol 的本地化字符串。
        /// </summary>
        public static string WeaponPistol {
            get {
                return ResourceManager.GetString("WeaponPistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weapons 的本地化字符串。
        /// </summary>
        public static string WeaponsShard {
            get {
                return ResourceManager.GetString("WeaponsShard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A pistol is available in nearby sidewalk. 的本地化字符串。
        /// </summary>
        public static string WeaponsShardSubtitle {
            get {
                return ResourceManager.GetString("WeaponsShardSubtitle", resourceCulture);
            }
        }
    }
}
