//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoArtifactLights.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoArtifactLights.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Carbine Rifle Ammo x50 的本地化字符串。
        /// </summary>
        public static string AmmuCarbineRifle {
            get {
                return ResourceManager.GetString("AmmuCarbineRifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A widely-used assault rifle, mostly used by security staffs and law enforcement agencies. 的本地化字符串。
        /// </summary>
        public static string AmmuCarbineRifleSubtitle {
            get {
                return ResourceManager.GetString("AmmuCarbineRifleSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press ~INPUT_CONTEXT~ to buy weapons. 的本地化字符串。
        /// </summary>
        public static string AmmuOpenShop {
            get {
                return ResourceManager.GetString("AmmuOpenShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pistol Ammo x50 的本地化字符串。
        /// </summary>
        public static string AmmuPistol {
            get {
                return ResourceManager.GetString("AmmuPistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard pistol, suitable for self defense. 的本地化字符串。
        /// </summary>
        public static string AmmuPistolSubtitle {
            get {
                return ResourceManager.GetString("AmmuPistolSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pump Shotgun Ammo x20 的本地化字符串。
        /// </summary>
        public static string AmmuPumpShotgun {
            get {
                return ResourceManager.GetString("AmmuPumpShotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard shotgun for self defense purposes. 的本地化字符串。
        /// </summary>
        public static string AmmuPumpShotgunSubtitle {
            get {
                return ResourceManager.GetString("AmmuPumpShotgunSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weapon Shop 的本地化字符串。
        /// </summary>
        public static string AmmuSubtitle {
            get {
                return ResourceManager.GetString("AmmuSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AmmuNation 的本地化字符串。
        /// </summary>
        public static string AmmuTitle {
            get {
                return ResourceManager.GetString("AmmuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Armed NPC Kill Bonus +$10 的本地化字符串。
        /// </summary>
        public static string ArmedBonus {
            get {
                return ResourceManager.GetString("ArmedBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exchange failed because your bank account has reached 32-bit integer limit. 的本地化字符串。
        /// </summary>
        public static string BankMaximum {
            get {
                return ResourceManager.GetString("BankMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hungry 的本地化字符串。
        /// </summary>
        public static string BarHungry {
            get {
                return ResourceManager.GetString("BarHungry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Water 的本地化字符串。
        /// </summary>
        public static string BarWater {
            get {
                return ResourceManager.GetString("BarWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You already ~h~has~s~~b~ body armor~s~. 的本地化字符串。
        /// </summary>
        public static string BodyArmorAlreadyHad {
            get {
                return ResourceManager.GetString("BodyArmorAlreadyHad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have enough money for this. 的本地化字符串。
        /// </summary>
        public static string BuyNoMoney {
            get {
                return ResourceManager.GetString("BuyNoMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exchange failed because your cash amount has reached 32-bit integer limit. 的本地化字符串。
        /// </summary>
        public static string CashMaximum {
            get {
                return ResourceManager.GetString("CashMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You don&apos;t have enough cash to deposit. 的本地化字符串。
        /// </summary>
        public static string DepositNoMoney {
            get {
                return ResourceManager.GetString("DepositNoMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have a ~h~deprecated save~s~ in your NOAR save directory. It will no longer be loaded. 的本地化字符串。
        /// </summary>
        public static string DeprecatedXMLSave {
            get {
                return ResourceManager.GetString("DeprecatedXMLSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Carbine Rifle 的本地化字符串。
        /// </summary>
        public static string DifficultyCarbineRifle {
            get {
                return ResourceManager.GetString("DifficultyCarbineRifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Difficulty Changed 的本地化字符串。
        /// </summary>
        public static string DifficultyChange {
            get {
                return ResourceManager.GetString("DifficultyChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Easy 的本地化字符串。
        /// </summary>
        public static string DifficultyEasy {
            get {
                return ResourceManager.GetString("DifficultyEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hard 的本地化字符串。
        /// </summary>
        public static string DifficultyHard {
            get {
                return ResourceManager.GetString("DifficultyHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Difficulty has been upgraded to {0}. Ambient NPCs will now use {0}. 的本地化字符串。
        /// </summary>
        public static string DifficultyHelp {
            get {
                return ResourceManager.GetString("DifficultyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initial 的本地化字符串。
        /// </summary>
        public static string DifficultyInitial {
            get {
                return ResourceManager.GetString("DifficultyInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Micro SMGs 的本地化字符串。
        /// </summary>
        public static string DifficultyMicroSmg {
            get {
                return ResourceManager.GetString("DifficultyMicroSmg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nether 的本地化字符串。
        /// </summary>
        public static string DifficultyNether {
            get {
                return ResourceManager.GetString("DifficultyNether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        public static string DifficultyNormal {
            get {
                return ResourceManager.GetString("DifficultyNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pump Shotguns 的本地化字符串。
        /// </summary>
        public static string DifficultyPumpShotgun {
            get {
                return ResourceManager.GetString("DifficultyPumpShotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rocket Launchers 的本地化字符串。
        /// </summary>
        public static string DifficultyRPG {
            get {
                return ResourceManager.GetString("DifficultyRPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Difficulty has been upgraded to {0}. 的本地化字符串。
        /// </summary>
        public static string DifficultyShard {
            get {
                return ResourceManager.GetString("DifficultyShard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NoArtifactLights has encountered error and must exit. 的本地化字符串。
        /// </summary>
        public static string ExceptionMain {
            get {
                return ResourceManager.GetString("ExceptionMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NoArtifactLights menu has encountered error and menu is disabled. 的本地化字符串。
        /// </summary>
        public static string ExceptionMenu {
            get {
                return ResourceManager.GetString("ExceptionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exchange Failed 的本地化字符串。
        /// </summary>
        public static string ExchangeNotificationFailed {
            get {
                return ResourceManager.GetString("ExchangeNotificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have killed a person. Once you killed amount of persons, the difficulty will upgrade. 的本地化字符串。
        /// </summary>
        public static string FirstKill {
            get {
                return ResourceManager.GetString("FirstKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hamburger 的本地化字符串。
        /// </summary>
        public static string FoodBurger {
            get {
                return ResourceManager.GetString("FoodBurger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chicken 的本地化字符串。
        /// </summary>
        public static string FoodChicken {
            get {
                return ResourceManager.GetString("FoodChicken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press ~INPUT_CONTEXT~ to open shop. 的本地化字符串。
        /// </summary>
        public static string FoodOpenShop {
            get {
                return ResourceManager.GetString("FoodOpenShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The game has been ~b~loaded~s~. 的本地化字符串。
        /// </summary>
        public static string GameLoaded {
            get {
                return ResourceManager.GetString("GameLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The game has been ~b~saved~s~. 的本地化字符串。
        /// </summary>
        public static string GameSaved {
            get {
                return ResourceManager.GetString("GameSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are now hungry and needs some food. 的本地化字符串。
        /// </summary>
        public static string Hungry {
            get {
                return ResourceManager.GetString("Hungry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You may only enter numbers. 的本地化字符串。
        /// </summary>
        public static string InputNotNumber {
            get {
                return ResourceManager.GetString("InputNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View current bank account currency. 的本地化字符串。
        /// </summary>
        public static string ItemBankSubtitle {
            get {
                return ResourceManager.GetString("ItemBankSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currency 的本地化字符串。
        /// </summary>
        public static string ItemBankTitle {
            get {
                return ResourceManager.GetString("ItemBankTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Views current cash. 的本地化字符串。
        /// </summary>
        public static string ItemCashSubtitle {
            get {
                return ResourceManager.GetString("ItemCashSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cash 的本地化字符串。
        /// </summary>
        public static string ItemCashTitle {
            get {
                return ResourceManager.GetString("ItemCashTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Call for police assistence. 的本地化字符串。
        /// </summary>
        public static string ItemCopsSubtitle {
            get {
                return ResourceManager.GetString("ItemCopsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Call for Cops 的本地化字符串。
        /// </summary>
        public static string ItemCopsTitle {
            get {
                return ResourceManager.GetString("ItemCopsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deposits cash into bank account. 的本地化字符串。
        /// </summary>
        public static string ItemDepositSubtitle {
            get {
                return ResourceManager.GetString("ItemDepositSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deposit 的本地化字符串。
        /// </summary>
        public static string ItemDepositTitle {
            get {
                return ResourceManager.GetString("ItemDepositTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Difficulty 的本地化字符串。
        /// </summary>
        public static string ItemDifficulty {
            get {
                return ResourceManager.GetString("ItemDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Views current difficulty. 的本地化字符串。
        /// </summary>
        public static string ItemDIfficultySubtitle {
            get {
                return ResourceManager.GetString("ItemDIfficultySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kills 的本地化字符串。
        /// </summary>
        public static string ItemKills {
            get {
                return ResourceManager.GetString("ItemKills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Views current kills. 的本地化字符串。
        /// </summary>
        public static string ItemKillsSubtitle {
            get {
                return ResourceManager.GetString("ItemKillsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sets whether the lights have out of San Andreas or not. 的本地化字符串。
        /// </summary>
        public static string ItemLightsSubtitle {
            get {
                return ResourceManager.GetString("ItemLightsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blackout 的本地化字符串。
        /// </summary>
        public static string ItemLightsTitle {
            get {
                return ResourceManager.GetString("ItemLightsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loads the game from save. 的本地化字符串。
        /// </summary>
        public static string ItemLoadSubtitle {
            get {
                return ResourceManager.GetString("ItemLoadSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Game 的本地化字符串。
        /// </summary>
        public static string ItemLoadTitle {
            get {
                return ResourceManager.GetString("ItemLoadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appearance 的本地化字符串。
        /// </summary>
        public static string ItemModels {
            get {
                return ResourceManager.GetString("ItemModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change your look and feel. 的本地化字符串。
        /// </summary>
        public static string ItemModelsDescription {
            get {
                return ResourceManager.GetString("ItemModelsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saves the current game status. 的本地化字符串。
        /// </summary>
        public static string ItemSaveSubtitle {
            get {
                return ResourceManager.GetString("ItemSaveSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Game 的本地化字符串。
        /// </summary>
        public static string ItemSaveTitle {
            get {
                return ResourceManager.GetString("ItemSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sells current vehicle. The car will be locked and you will receive NAL$. 的本地化字符串。
        /// </summary>
        public static string ItemSellCarSubtitle {
            get {
                return ResourceManager.GetString("ItemSellCarSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sell Vehicle 的本地化字符串。
        /// </summary>
        public static string ItemSellCarTitle {
            get {
                return ResourceManager.GetString("ItemSellCarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottle of Water 的本地化字符串。
        /// </summary>
        public static string ItemWater {
            get {
                return ResourceManager.GetString("ItemWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Withdraws currency into cash. 的本地化字符串。
        /// </summary>
        public static string ItemWithdrawSubtitle {
            get {
                return ResourceManager.GetString("ItemWithdrawSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Withdraw 的本地化字符串。
        /// </summary>
        public static string ItemWithdrawTitle {
            get {
                return ResourceManager.GetString("ItemWithdrawTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maze Bank 的本地化字符串。
        /// </summary>
        public static string MazeBank {
            get {
                return ResourceManager.GetString("MazeBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Food Shop 的本地化字符串。
        /// </summary>
        public static string MenuFoodShopSubtitle {
            get {
                return ResourceManager.GetString("MenuFoodShopSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Menu 的本地化字符串。
        /// </summary>
        public static string MenuMainTitle {
            get {
                return ResourceManager.GetString("MenuMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deals Menu 的本地化字符串。
        /// </summary>
        public static string MenuMarketSubtitle {
            get {
                return ResourceManager.GetString("MenuMarketSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Market 的本地化字符串。
        /// </summary>
        public static string MenuMarketTitle {
            get {
                return ResourceManager.GetString("MenuMarketTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Models 的本地化字符串。
        /// </summary>
        public static string MenuModel {
            get {
                return ResourceManager.GetString("MenuModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~r~Warning~s~: You must use this mod together with ~b~MrTank&apos;s~h~ Player Death No Reset Model~s~ script or ~r~you will stuck~s~ on death screen. 的本地化字符串。
        /// </summary>
        public static string NoModelWarning {
            get {
                return ResourceManager.GetString("NoModelWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can download it from ~b~GTA5-Mods~s~. 的本地化字符串。
        /// </summary>
        public static string NoModelWarning2 {
            get {
                return ResourceManager.GetString("NoModelWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have a save file. 的本地化字符串。
        /// </summary>
        public static string NoSave {
            get {
                return ResourceManager.GetString("NoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 joined the game. 的本地化字符串。
        /// </summary>
        public static string PlayerJoinedGame {
            get {
                return ResourceManager.GetString("PlayerJoinedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vehicle Repair 的本地化字符串。
        /// </summary>
        public static string RepairBlip {
            get {
                return ResourceManager.GetString("RepairBlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press ~INPUT_CONTEXT~ to repair your current vehicle. 的本地化字符串。
        /// </summary>
        public static string RepairHelp {
            get {
                return ResourceManager.GetString("RepairHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your vehicle has been repaired. 的本地化字符串。
        /// </summary>
        public static string RepairSuccess {
            get {
                return ResourceManager.GetString("RepairSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your vehicle is intact. 的本地化字符串。
        /// </summary>
        public static string RepairUndamaged {
            get {
                return ResourceManager.GetString("RepairUndamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~h~Attention!~s~ This save is not available in this version of NoArtifactLights. 的本地化字符串。
        /// </summary>
        public static string SaveVersion {
            get {
                return ResourceManager.GetString("SaveVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You currently does not in a vehicle. Get in the car you wanna sell. 的本地化字符串。
        /// </summary>
        public static string SellNoCar {
            get {
                return ResourceManager.GetString("SellNoCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are already full and cannot eat anymore. 的本地化字符串。
        /// </summary>
        public static string SellNotHungry {
            get {
                return ResourceManager.GetString("SellNotHungry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have successfully selled your vehicle. 的本地化字符串。
        /// </summary>
        public static string SellSuccess {
            get {
                return ResourceManager.GetString("SellSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to NoArtifactLights survival modification.  的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destory stolen delivery bonus +$100 的本地化字符串。
        /// </summary>
        public static string StolenDelivery {
            get {
                return ResourceManager.GetString("StolenDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The transaction was success. 的本地化字符串。
        /// </summary>
        public static string TransactionSuccess {
            get {
                return ResourceManager.GetString("TransactionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~h~Unloading mod~s~. ~b~Bye!~s~ 的本地化字符串。
        /// </summary>
        public static string Unload {
            get {
                return ResourceManager.GetString("Unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are dehydrating. Go to a shop to refill your water. 的本地化字符串。
        /// </summary>
        public static string WaterTooLow {
            get {
                return ResourceManager.GetString("WaterTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body Armor 的本地化字符串。
        /// </summary>
        public static string WeaponBodyArmor {
            get {
                return ResourceManager.GetString("WeaponBodyArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A standard armor that can provides protection to ammos and explosions. 的本地化字符串。
        /// </summary>
        public static string WeaponBodyArmorDescription {
            get {
                return ResourceManager.GetString("WeaponBodyArmorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pistol 的本地化字符串。
        /// </summary>
        public static string WeaponPistol {
            get {
                return ResourceManager.GetString("WeaponPistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weapons 的本地化字符串。
        /// </summary>
        public static string WeaponsShard {
            get {
                return ResourceManager.GetString("WeaponsShard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A pistol is available in nearby sidewalk. 的本地化字符串。
        /// </summary>
        public static string WeaponsShardSubtitle {
            get {
                return ResourceManager.GetString("WeaponsShardSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You don&apos;t have enough currency to withdraw. 的本地化字符串。
        /// </summary>
        public static string WithdrawNoCurrency {
            get {
                return ResourceManager.GetString("WithdrawNoCurrency", resourceCulture);
            }
        }
    }
}
